#!/bin/sh
python tests.py
error=$? # Код возврата предыдущей команды
if [ "$error" -eq 0 ]
then
    echo "Кажется, всё в порядке. Коммитим"
    exit 0
else
    echo "Тесты не прошли проверку. Коммитить не будем"
    exit 1
fi